### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Nixuri** [sooxt98/spotify-crack-chrome-app#11]

**Comment by sooxt98** [comment]
https://github.com/sooxt98/spotify-crack-chrome-app/commit/240ae41ee871243b20fac3026d33bf93de19e913

**Comment by badlandspray** [comment]
https://github.com/sooxt98/spotify-crack-chrome-app/commit/240ae41ee871243b20fac3026d33bf93de19e913 didn't fix it, In case of consecutive ads it doesn't play the next song in the queue after ad is finished, it pauses there. I've to reload the page and manually select the song.
