### ISSUE TITLE
Problem with different languages

### ISSUE THREAD

**Issue by pms967** [sooxt98/spotify-crack-chrome-app#6]
Upgrade button suppression does not work in (some?) other language. E.g., for Italian language this patch needs to be applied:

`--- style.css~	2020-09-05 11:06:56.000000000 +0200`
`+++ style.css	2021-01-26 15:12:45.527342813 +0100`
`@@ -1,3 +1,3 @@`
`-button[title="Upgrade to Premium"], div[data-testid="test-ref-div"] {`
`+button[title="Effettua l'upgrade a Premium"], div[data-testid="test-ref-div"] {`
`     display:none !important;`
` }`

I wonder if it could be possible to use a different (and language-invariant) way to identify that element...

**Comment by sooxt98** [comment]
https://github.com/sooxt98/spotify-crack-chrome-app/commit/92f44ba15422a5b04ea5cc441da2d3b0f9d0589a#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7a

**Comment by pms967** [comment]
> [92f44ba](https://github.com/sooxt98/spotify-crack-chrome-app/commit/92f44ba15422a5b04ea5cc441da2d3b0f9d0589a)

beware: my patch will only work if you have spoti interface in Italian. Can't be used as a general fix.
